---
- hosts: all
  become: true

  tasks:

    - name: Ensure uploads folder exists
      file:
        path: "/home/vagrant/uploads"
        state: directory
        mode: '0777'
        owner: vagrant
        group: vagrant

    - name: Add commands to .bashrc
      lineinfile:
        path: /home/vagrant/.bashrc
        line: '{{ item }}'
        create: yes
      with_items:
        - 'source {{ working_dir }}vagrant_venv/bin/activate'
        - 'cd {{ working_dir }}'
      when: ansible_user == 'vagrant'
