"""empty message

Revision ID: 22eac6cda529
Revises: add_avg_consumption
Create Date: 2025-12-11 08:28:15.277459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22eac6cda529'
down_revision = 'add_avg_consumption'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_consumption', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ds_metrics', schema=None) as batch_op:
        batch_op.drop_column('average_consumption')

    # ### end Alembic commands ###
