"""empty message

Revision ID: 493ad056a94e
Revises: 387ec035397d
Create Date: 2025-11-30 13:31:30.354396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493ad056a94e'
down_revision = '387ec035397d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coche',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=120), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=False),
    sa.Column('motor', sa.String(length=120), nullable=False),
    sa.Column('consumo', sa.Float(), nullable=False),
    sa.Column('combustible', sa.String(length=120), nullable=False),
    sa.Column('comienzo_de_produccion', sa.Integer(), nullable=False),
    sa.Column('fin_de_produccion', sa.Integer(), nullable=False),
    sa.Column('asientos', sa.Integer(), nullable=False),
    sa.Column('puertas', sa.Integer(), nullable=False),
    sa.Column('peso', sa.Integer(), nullable=False),
    sa.Column('carga_max', sa.Integer(), nullable=False),
    sa.Column('pais_de_origen', sa.String(length=120), nullable=False),
    sa.Column('precio_estimado', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=7), nullable=False),
    sa.Column('fecha_matriculacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coche')
    # ### end Alembic commands ###
