"""empty message

Revision ID: 5a2955a80c67
Revises: e1d3846f80fc
Create Date: 2025-11-29 20:15:43.577306

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a2955a80c67'
down_revision = 'e1d3846f80fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uvl_data_set')
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('DataSetType')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('DataSetType', mysql.VARCHAR(length=50), nullable=False))

    op.create_table('uvl_data_set',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['data_set.id'], name=op.f('uvl_data_set_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
