"""Add average_engine_size to DSMetrics

Revision ID: add_avg_engine_size
Revises: f4d61adc0e06
Create Date: 2025-12-10 19:30:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_avg_engine_size"
down_revision = "f4d61adc0e06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ds_metrics", schema=None) as batch_op:
        batch_op.add_column(sa.Column("average_engine_size", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ds_metrics", schema=None) as batch_op:
        batch_op.drop_column("average_engine_size")
    # ### end Alembic commands ###
