"""add_email_2fa_support

Revision ID: df115093c219
Revises: cfafdceca85f
Create Date: 2025-11-07 10:38:56.899837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df115093c219'
down_revision = 'cfafdceca85f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Create email_2fa_code table
    op.create_table('email_2fa_code',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('invalidated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Create two_fa_attempt table
    op.create_table('two_fa_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Add email_2fa_enabled column to user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_2fa_enabled', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove email_2fa_enabled column from user table
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_2fa_enabled')

    # Drop two_fa_attempt table
    op.drop_table('two_fa_attempt')

    # Drop email_2fa_code table
    op.drop_table('email_2fa_code')

    # ### end Alembic commands ###
